### ISSUE TITLE
Cosmetic Issue

### ISSUE THREAD

**Issue by miketweaver** [bueltge/Chosen-for-MantisBT#1]
This is a minor cosmetic issue. Everywhere I've seen, you've got the dropdown items on the left side of the screen. In the Manage -> Manage Plugins section they're centered. It would be better if you aligned it to the left to keep it consistent. 

![image](https://cloud.githubusercontent.com/assets/5581855/8759267/80a1e398-2cad-11e5-8522-d68f2a849783.png)

PS: I'm loving the look of this so far. Nice work.

**Comment by bueltge** [comment]
Thanks for the hint, it should be fixed now.
