### ISSUE TITLE
Unable to sort/search

### ISSUE THREAD

**Issue by sintaq83** [bueltge/Chosen-for-MantisBT#11]
Hi bueltge,

I just installed your wonderful plugin in my Mantis v2.2.4

The sort/search function seams doesnt work properly for some of the item within the list box.

**Comment by sintaq83** [comment]
@bueltge 
you may ignore/close my reported issue as i found the root cause. its more to how i setup the name in my mantis instance. the setup was something like this AB-SECTION-John Rose

hence when i type/search John, the result is null. but when i search Rosa, it appear.

**Comment by sintaq83** [comment]
thanks

**Comment by bueltge** [comment]
Thank you for the reply and clarification!
