### ISSUE TITLE
Chosen not display in mobile 

### ISSUE THREAD

**Issue by sintaq83** [bueltge/Chosen-for-MantisBT#12]
@bueltge 
Is it expected for Chosen not to display in mobile MantisBT?

**Comment by sintaq83** [comment]
@bueltge 
you may close this. anyway, thanks for this wonderful plugin.

**Comment by bueltge** [comment]
@sintaq83 Do you have no problems on the mobile view? Because I haven't test it for now.

**Comment by sintaq83** [comment]
Yes. I did have a problem on my mobile.

As such i have to custom a little bit of ur codes by checking whether users
are on mobile browser or desktop. If mobile browser, i dont load js and
stuff
