### ISSUE TITLE
Merge plugin with existing plugin JqueryChosen

### ISSUE THREAD

**Issue by roman-1983** [bueltge/Chosen-for-MantisBT#2]
https://github.com/mantisbt-plugins/JqueryChosen

**Comment by bueltge** [comment]
Same goal. I need this plugin as enhancement for my MantisBT theme Colorized, see this readme. 
How we can merge this to one plugin to rule them all? ;) what is your idea for this issue?

**Comment by bueltge** [comment]
The other plugin have the last update before 2 years, maybe not maintained?
I will close this issue here, to less feedback.
