### ISSUE TITLE
403 for mantisbt-1.3.0

### ISSUE THREAD

**Issue by Blaimi** [bueltge/Chosen-for-MantisBT#3]
Mantisbt-1.3.0 provides a .htaccess in the plugins-folder which forbids direct access. I had to create a new .htaccess.

`echo "allow from all" > plugins/chosen/.htaccess`

**Comment by Blaimi** [comment]
there is also a `/plugin_file.php`. Don’t know if that would be a better way to get the files. E.g. BBCodePlus uses this.

**Comment by bueltge** [comment]
I have tested it again, works really well, no problems.

**Comment by Blaimi** [comment]
this file blocks every access to the plugins folder. Depending on your server-config, this file is ignored.

https://github.com/mantisbt/mantisbt/blob/master/plugins/.htaccess

**Comment by bueltge** [comment]
Thanks for the hint @Blaimi I have change the version and now is include a htaccess rule to overwrite the access. Best.
