### ISSUE TITLE
Bug: Search shows blank &nbsp;

### ISSUE THREAD

**Issue by NeumannPSG** [bueltge/Chosen-for-MantisBT#5]
Hey,
The Select Box show the `&nbsp` - Charakter if you search for one of the four character and the remaining String contains the same.
e.g.:
 
![8942cef2-d7e9-11e6-9112-fa6857df34f8](https://cloud.githubusercontent.com/assets/133425/21844633/b9f02544-d7ef-11e6-875d-1d1821028a32.png)

**Comment by bueltge** [comment]
A error from chosen js library. I will fix this in my plugin.
reference to https://github.com/harvesthq/chosen/issues/2274

**Comment by bueltge** [comment]
The new version 1.2.0 should fixed this problem. My tests works fine.

**Comment by NeumannPSG** [comment]
Thanks for the fast fix, but the fix created a new Problem. The Combobox in the top right is now align right.
I tried to change this with the Custom_Css but that just fixes the title.

![1e186188-d98c-11e6-9130-aadb3f1a8c29](https://cloud.githubusercontent.com/assets/133425/21929430/baeb2cc6-d990-11e6-874d-1e7095201a2d.png)

**Comment by bueltge** [comment]
Yes, that's is the default style of MantisBT style - default.css; seelctor `#project-selector-div`. I can't change this via this plugin, this should change inside your theme or a an alternative theme like https://github.com/bueltge/MantisBT-Colorized
