### ISSUE TITLE
In 'View Issue' , Chosen plugin hides values

### ISSUE THREAD

**Issue by drspot** [bueltge/Chosen-for-MantisBT#7]
Hello,

I'm using Chosen plugin (see attached file for version) for MantisBT, version 2.1.0.
In 'View Issue' page, at the bottom, the combo box of action to be performed for selected issue, I cannot see values, since they are hided (see screenshot).
Since Chosen plugin is very useful for us, is there a way to change this behavior?
Additional info: this is tested with IE, Chrome and FF --> same behavior
![chosenbug](https://user-images.githubusercontent.com/30691238/28918964-bbc5013a-784b-11e7-8ff1-6bed25c30410.jpg)
![choseninfo](https://user-images.githubusercontent.com/30691238/28918997-d661409e-784b-11e7-84e4-3061e4b77c62.JPG)
Thank you in advance

**Comment by bueltge** [comment]
Thanks for the usage and hint. Currently I haven't a 2.* installation for fixing this, so that I will install a 2* version and look for your problem. 
Best.

**Comment by drspot** [comment]
@bueltge Thank you for your feedback! Do you have a rough idea about when you could have a look on it, and let me know if it is fixable? Thanks in advance!

Best.

**Comment by bueltge** [comment]
Hi @drspot 
please add your configuration for your status. I f I check this with an default installation, always the topic is non existent for me, because all status are to short for your problem. thx. 
![mantisbt-status-13](https://user-images.githubusercontent.com/133425/29774565-2145ce94-8c02-11e7-8ba8-4dcbd72b2acc.png)

**Comment by drspot** [comment]
Hi @bueltge ,

here attached, you can find 2 files:
- Configuration01.jpg : how it appears at first access
![configuration01](https://user-images.githubusercontent.com/30691238/29776572-4cd2358c-8c09-11e7-8a0f-adb7c4234c48.jpg)

- Configuration02.jpg : how it appears if you choose the longest sentence in the combo
![configuration02](https://user-images.githubusercontent.com/30691238/29776606-6e8a49c6-8c09-11e7-89ac-55a667926991.jpg)

It seems like it aligns combo keeping the right side position of the box, while it should use the left side...
Best

**Comment by drspot** [comment]
BTW, the marked entry in previous 'Configuration02.jpg' screenshot is the longest I have

**Comment by bueltge** [comment]
You can download a new version that should fixed this issue https://github.com/bueltge/Chosen-for-MantisBT/releases/tag/1.2.2
Please try this and give feedback. If is fine, I will release that version.
Best.

**Comment by drspot** [comment]
Unfortunately, with 1.2.2 I have the same behavior...  Shouldn't it be aligned to the left instead?
![immagine](https://user-images.githubusercontent.com/30691238/29778077-69f271e0-8c0e-11e7-82c9-d42b01e93baa.jpg)

**Comment by bueltge** [comment]
Have you reload the page, flush cache in your browser? Is your Mantis online, so that I can see this problem?

**Comment by drspot** [comment]
Yes, I have reloaded and cleared the cache , but problem still there.
Mantis is on our intranet , not online

**Comment by bueltge** [comment]
Please check this. Load your mantis in Chrome, then F12 for the Webinspector. 
Now use the selector, Ctrl+Shif+c or 1. in my screen. 
Find the element and it should selected.
get me the same screenshot, so that I see the 4. on the right side, the css rule. You should habe the same rules from 4. If not, if is not reloaded, is the old version.
![mantisbt-f12](https://user-images.githubusercontent.com/133425/29778828-f3e2b87c-8c10-11e7-9fa7-057188a2ab2d.png)

**Comment by drspot** [comment]
![image](https://user-images.githubusercontent.com/30691238/29779194-1b147024-8c12-11e7-8136-7048b546f35f.png)
Here you are

**Comment by bueltge** [comment]
You are really shure, that you have copy the css files of the plugin? Especially the `chosen.min.css` in `lib/`

Please check your `mantis-url.com/plugins/chosen/lib/chosen.min.css` and search in this file `.chosen-container.chosen-with-drop .chosen-drop`. The rules for this selector should have `{right:auto;z-index:9999}`

**Comment by drspot** [comment]
yes, I'm sure
![image](https://user-images.githubusercontent.com/30691238/29808709-7c7b69d0-8c99-11e7-8808-c02a9c7d86be.png)

**Comment by drspot** [comment]
You mean that you have tried with a very long entry as I have, and in your installation everything works as expected?

**Comment by drspot** [comment]
Hi @bueltge ,
I've tried to modify CSS, and here the results:
![immagine](https://user-images.githubusercontent.com/30691238/29810833-ab250c70-8ca1-11e7-94c7-ccdceb2547f7.jpg)

This is exactly what I need! 
The changes in CSS are the following:
![image](https://user-images.githubusercontent.com/30691238/29810855-c3b696be-8ca1-11e7-957c-98234ebd7249.png)

LEFT instead of RIGHT

Is this ok or should it have some unwanted side effects?
Best

**Comment by bueltge** [comment]
That's works not for me. I have your result of the screenshot, if I use `right`.  Your solution should only works, if you add `left: auto; right: auto;`. Please try this, Thx.

**Comment by bueltge** [comment]
I have implement, so that you can download the current master for a valid test - https://github.com/bueltge/Chosen-for-MantisBT/archive/master.zip

**Comment by drspot** [comment]
It works! Thank you!

**Comment by bueltge** [comment]
Thanks for your tests, feedback. The version is now  online, taged as 1.2.2.
