### ISSUE TITLE
Only works with whole strings

### ISSUE THREAD

**Issue by realmofevil** [bueltge/Chosen-for-MantisBT#8]
If you type a part of the string you are looking for, it won't work. Also, I've found this one here https://www.allphptricks.com/select-box-with-search-option-using-jquery/ which does search for incomplete parts in the strings and thought you might want to see it.

**Comment by bueltge** [comment]
The plugin is no addon for the search, don't change the search query or similar. The plugin enhance the select areas, boxes for better user experience. 
>Chosen is a jQuery plugin that makes long, unwieldy select boxes much more user-friendly.
SO I'm not sure what you mean in the context of the plugin?

**Comment by realmofevil** [comment]
I meant that if you type, e.g. a partial username or something else in a select box - it won't work unless you type the string with its starting characters. If you want to find "username" you can't do it by typing just "name", you have to type "user". So I guess I will have to make it into a new plugin myself?

**Comment by bueltge** [comment]
Yes, I understand that. However is it not a part of the plugin to enhance the search query. The idea is great, you should create a plugin for Mantis. But which version do you use?

**Comment by realmofevil** [comment]
I'm using MantisBT 2.22.0 at the moment and your plugin seems to be working fine with it. At least from the brief testing I did.

Okay, will try and see what happens with the search feature in a new plugin.
